version: '3'
services:
    client:
        build:
            context: ./packages/client
            dockerfile: Dockerfile.dev
        volumes:
            - /client/node_modules
            - ./packages/client:/client
        environment:
            - CHOKIDAR_USEPOLLING=true
    api:
        build:
            context: ./packages/api
            dockerfile: Dockerfile.dev
        volumes:
            - /api/node_modules
            - ./packages/api:/api
        depends_on:
            - mongodb
        environment:
            WAIT_HOSTS: mongodb:27017
        links:
            - mongodb
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        command: mongod --noauth
    nginx:
        restart: always
        build:
            context: ./packages/nginx
            dockerfile: Dockerfile.dev
        ports:
            - '8000:443'
        volumes:
            - ./packages/nginx/default.conf:/etc/nginx/conf.d/default.conf
    cac:
        restart: always
        build:
            context: ./packages/cac
            dockerfile: Dockerfile.dev
        ports:
            - '7000:443'
        volumes:
            - ./packages/cac/default.conf:/etc/nginx/conf.d/default.conf
            - ./packages/cac/index.html:/www/data/index.html
