version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /client/node_modules
      - ./client:/client
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /api/node_modules
      - ./api:/api
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    command: mongod --noauth
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8000:443"
