version: '3'
services:
    client:
        build:
            context: ./
            dockerfile: ./client/Dockerfile.dev
        volumes:
            - ./client:/packages/client
            - ./shared:/packages/shared
            - /packages/client/node_modules
            - /packages/shared/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
    api:
        build:
            context: ./
            dockerfile: ./api/Dockerfile.dev
        volumes:
            - ./api:/packages/api
            - ./shared:/packages/shared
            - /packages/api/node_modules
            - /packages/shared/node_modules
        ports:
            - 9000:9000
        depends_on:
            - mongodb
        environment:
            WAIT_HOSTS: mongodb:27017
        links:
            - mongodb
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        command: mongod --noauth
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - '8000:443'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    cac:
        restart: always
        build:
            context: ./cac
            dockerfile: Dockerfile.dev
        ports:
            - '7000:443'
        volumes:
            - ./cac/default.conf:/etc/nginx/conf.d/default.conf
            - ./cac/index.html:/www/data/index.html
            - ./cac/400.html:/www/data/400.html
