version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /client/node_modules
      - ./client:/client
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports: 
      - "9000:9000"
    volumes:
      - /api/node_modules
      - ./api:/api
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
    links:
      - mongodb  
  mongodb:
        image: mongo
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles