apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: "2020-02-13T20:03:58Z"
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: default
spec:
  ports:
  - nodePort: 31387
    port: 8000
    protocol: TCP
    targetPort: 443
  selector:
    io.kompose.service: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
