FROM node:alpine
WORKDIR '/api'
COPY ./package.json ./
RUN npm install
COPY . .
## THE LIFE SAVER
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

## Launch the wait tool and then your application
CMD /wait && npm run dev